/**
 * Auto-generated template module
 * Generated by vite-plugin-templates
 * Generated: 2025-08-14T17:08:07.482Z
 * Contains all framework templates compiled as JavaScript strings
 */

// Template registry
const templates = {};

// Template: auth/pages/ForgotPasswordPage.mst
templates['auth/pages/ForgotPasswordPage.mst'] = `<div class="auth-page forgot-password-page min-vh-100 d-flex align-items-center py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-lg border-0">
                    <div class="card-body p-4 p-md-5">
                        <!-- Logo and Header -->
                        <div class="text-center mb-4">
                            {{#logoUrl}}
                            <img src="{{logoUrl}}" alt="{{appName}}" class="mb-3" style="max-height: 60px;">
                            {{/logoUrl}}
                            <h2 class="h3 mb-2">{{messages.forgotTitle}}</h2>
                            <p class="text-muted">{{messages.forgotSubtitle}}</p>
                        </div>

                        <!-- Error Alert -->
                        {{#error}}
                        <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
                            <i class="bi bi-exclamation-triangle-fill me-2"></i>
                            <div>{{error}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {{/error}}

                        <!-- Success Message -->
                        {{#success}}
                        <div class="alert alert-success d-flex align-items-center" role="alert">
                            <i class="bi bi-check-circle-fill me-2"></i>
                            <div>
                                <strong>Success!</strong><br>
                                {{#successMessage}}{{successMessage}}{{/successMessage}}
                                {{^successMessage}}Password reset instructions have been sent to your email.{{/successMessage}}
                            </div>
                        </div>

                        <div class="text-center">
                            <p class="mb-3">
                                <i class="bi bi-envelope-check text-success" style="font-size: 3rem;"></i>
                            </p>
                            <p class="text-muted">
                                Please check your email inbox and follow the instructions to reset your password.
                                The link will expire in 24 hours.
                            </p>
                            <div class="d-grid gap-2 mt-4">
                                <button
                                    class="btn btn-outline-primary btn-lg"
                                    data-action="backToLogin">
                                    <i class="bi bi-arrow-left me-2"></i>Back to Login
                                </button>
                                <button
                                    class="btn btn-link text-muted"
                                    data-action="resendEmail">
                                    Didn't receive email? Try again
                                </button>
                            </div>
                        </div>
                        {{/success}}

                        <!-- Reset Form -->
                        {{^success}}
                        <form data-action="resetPassword" novalidate>
                            <div class="mb-3">
                                <label for="forgotEmail" class="form-label">
                                    <i class="bi bi-envelope me-1"></i>Email Address
                                </label>
                                <input
                                    type="email"
                                    class="form-control form-control-lg"
                                    id="forgotEmail"
                                    placeholder="Enter your registered email"
                                    value="{{email}}"
                                    data-field="email"
                                    data-action="updateField"
                                    data-action-keydown="handleKeyPress"
                                    required
                                    autofocus
                                    {{#isLoading}}disabled{{/isLoading}}>
                                <div class="form-text">
                                    We'll send you a link to reset your password.
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <button
                                type="submit"
                                class="btn btn-primary btn-lg w-100 mb-3"
                                {{#isLoading}}disabled{{/isLoading}}>
                                {{#isLoading}}
                                <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                                Sending instructions...
                                {{/isLoading}}
                                {{^isLoading}}
                                <i class="bi bi-send me-2"></i>Send Reset Instructions
                                {{/isLoading}}
                            </button>

                            <!-- Back to Login -->
                            <button
                                type="button"
                                class="btn btn-outline-secondary btn-lg w-100"
                                data-action="backToLogin"
                                {{#isLoading}}disabled{{/isLoading}}>
                                <i class="bi bi-arrow-left me-2"></i>Back to Login
                            </button>
                        </form>

                        <!-- Additional Links -->
                        <div class="text-center mt-4">
                            <p class="text-muted mb-2">
                                Remember your password?
                                <a href="#" class="text-decoration-none fw-semibold" data-action="backToLogin">
                                    Sign in
                                </a>
                            </p>
                            <p class="text-muted mb-0">
                                Don't have an account?
                                <a href="#" class="text-decoration-none fw-semibold" data-action="register">
                                    Sign up
                                </a>
                            </p>
                        </div>
                        {{/success}}
                    </div>
                </div>

                <!-- Additional Help Text -->
                <div class="text-center mt-3">
                    <small class="text-muted">
                        <i class="bi bi-question-circle me-1"></i>
                        Need help? <a href="mailto:support@{{appName}}" class="text-decoration-none">Contact Support</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.auth-page {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.auth-page .card {
    backdrop-filter: blur(10px);
    background: rgba(255, 255, 255, 0.98);
    border-radius: 1rem;
}

.auth-page .form-control:focus {
    border-color: #667eea;
    box-shadow: 0 0 0 0.25rem rgba(102, 126, 234, 0.25);
}

.auth-page .btn-primary {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border: none;
}

.auth-page .btn-primary:hover:not(:disabled) {
    background: linear-gradient(135deg, #5a6fd4 0%, #68428e 100%);
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
}

.auth-page .btn-outline-primary:hover:not(:disabled),
.auth-page .btn-outline-secondary:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.auth-page a {
    color: #667eea;
}

.auth-page a:hover {
    color: #5a6fd4;
}
</style>
`;

// Template: auth/pages/LoginPage.mst
templates['auth/pages/LoginPage.mst'] = `<div class="auth-page login-page min-vh-100 d-flex align-items-center py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-lg border-0">
                    <div class="card-body p-4 p-md-5">
                        <!-- Logo and Header -->
                        <div class="text-center mb-4">
                            {{#logoUrl}}
                            <img src="{{logoUrl}}" alt="{{appName}}" class="mb-3" style="max-height: 60px;">
                            {{/logoUrl}}
                            <h2 class="h3 mb-2">{{messages.loginTitle}}</h2>
                            <p class="text-muted">{{messages.loginSubtitle}}</p>
                        </div>

                        <!-- Error Alert -->
                        {{#error}}
                        <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
                            <i class="bi bi-exclamation-triangle-fill me-2"></i>
                            <div>{{error}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {{/error}}

                        <!-- Login Form -->
                        <form data-action="login" novalidate>
                            <!-- Email Field -->
                            <div class="mb-3">
                                <label for="loginEmail" class="form-label">
                                    <i class="bi bi-envelope me-1"></i>Email Address
                                </label>
                                <input
                                    type="email"
                                    class="form-control form-control-lg"
                                    id="loginEmail"
                                    placeholder="name@example.com"
                                    value="{{email}}"
                                    data-field="email"
                                    data-action="updateField"
                                    data-action-keydown="handleKeyPress"
                                    required
                                    {{#isLoading}}disabled{{/isLoading}}>
                            </div>

                            <!-- Password Field -->
                            <div class="mb-3">
                                <label for="loginPassword" class="form-label">
                                    <i class="bi bi-lock me-1"></i>Password
                                </label>
                                <div class="input-group">
                                    <input
                                        type="{{#showPassword}}text{{/showPassword}}{{^showPassword}}password{{/showPassword}}"
                                        class="form-control form-control-lg"
                                        id="loginPassword"
                                        placeholder="Enter your password"
                                        value="{{password}}"
                                        data-field="password"
                                        data-action="updateField"
                                        data-action-keydown="handleKeyPress"
                                        required
                                        {{#isLoading}}disabled{{/isLoading}}>
                                    <button
                                        class="btn btn-outline-secondary"
                                        type="button"
                                        data-action="togglePassword"
                                        {{#isLoading}}disabled{{/isLoading}}>
                                        <i class="bi bi-eye{{#showPassword}}-slash{{/showPassword}}"></i>
                                    </button>
                                </div>
                            </div>

                            <!-- Remember Me & Forgot Password -->
                            <div class="d-flex justify-content-between align-items-center mb-4">
                                {{#enableRememberMe}}
                                <div class="form-check">
                                    <input
                                        class="form-check-input"
                                        type="checkbox"
                                        id="rememberMe"
                                        data-field="rememberMe"
                                        data-action="updateField"
                                        {{#rememberMe}}checked{{/rememberMe}}
                                        {{#isLoading}}disabled{{/isLoading}}>
                                    <label class="form-check-label" for="rememberMe">
                                        Remember me
                                    </label>
                                </div>
                                {{/enableRememberMe}}

                                {{#enableForgotPassword}}
                                <a href="#" class="text-decoration-none" data-action="forgotPassword">
                                    Forgot password?
                                </a>
                                {{/enableForgotPassword}}
                            </div>

                            <!-- Login Button -->
                            <button
                                type="submit"
                                class="btn btn-primary btn-lg w-100 mb-3"
                                {{#isLoading}}disabled{{/isLoading}}>
                                {{#isLoading}}
                                <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                                Signing in...
                                {{/isLoading}}
                                {{^isLoading}}
                                <i class="bi bi-box-arrow-in-right me-2"></i>Sign In
                                {{/isLoading}}
                            </button>

                            <!-- Alternative Login Methods -->
                            {{#passkeySupported}}
                            <div class="position-relative my-3">
                                <hr class="text-muted">
                                <span class="position-absolute top-50 start-50 translate-middle bg-white px-3 text-muted small">
                                    OR
                                </span>
                            </div>

                            <button
                                type="button"
                                class="btn btn-outline-primary btn-lg w-100 mb-2"
                                data-action="loginWithPasskey"
                                {{#isLoading}}disabled{{/isLoading}}>
                                <i class="bi bi-fingerprint me-2"></i>Sign in with Passkey
                            </button>
                            {{/passkeySupported}}

                            {{#googleEnabled}}
                            {{^passkeySupported}}
                            <div class="position-relative my-3">
                                <hr class="text-muted">
                                <span class="position-absolute top-50 start-50 translate-middle bg-white px-3 text-muted small">
                                    OR
                                </span>
                            </div>
                            {{/passkeySupported}}

                            <button
                                type="button"
                                class="btn btn-outline-danger btn-lg w-100 mb-2"
                                data-action="loginWithGoogle"
                                {{#isLoading}}disabled{{/isLoading}}>
                                <i class="bi bi-google me-2"></i>Sign in with Google
                            </button>
                            {{/googleEnabled}}
                        </form>

                        <!-- Register Link -->
                        <div class="text-center mt-4">
                            <p class="mb-0">
                                Don't have an account?
                                <a href="#" class="text-decoration-none fw-semibold" data-action="register">
                                    Sign up
                                </a>
                            </p>
                        </div>

                        <!-- Terms and Privacy -->
                        {{#termsUrl}}
                        <div class="text-center mt-3">
                            <small class="text-muted">
                                By signing in, you agree to our
                                <a href="#" class="text-decoration-none" data-url="{{termsUrl}}" data-action="openLink">
                                    Terms of Service
                                </a>
                                {{#privacyUrl}}
                                and
                                <a href="#" class="text-decoration-none" data-url="{{privacyUrl}}" data-action="openLink">
                                    Privacy Policy
                                </a>
                                {{/privacyUrl}}
                            </small>
                        </div>
                        {{/termsUrl}}
                    </div>
                </div>

                <!-- Additional Help Text -->
                <div class="text-center mt-3">
                    <small class="text-muted">
                        <i class="bi bi-shield-check me-1"></i>Secure Login with 256-bit Encryption
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.auth-page {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.auth-page .card {
    backdrop-filter: blur(10px);
    background: rgba(255, 255, 255, 0.98);
    border-radius: 1rem;
}

.auth-page .form-control:focus,
.auth-page .form-check-input:focus {
    border-color: #667eea;
    box-shadow: 0 0 0 0.25rem rgba(102, 126, 234, 0.25);
}

.auth-page .btn-primary {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border: none;
}

.auth-page .btn-primary:hover:not(:disabled) {
    background: linear-gradient(135deg, #5a6fd4 0%, #68428e 100%);
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
}

.auth-page .btn-outline-primary:hover:not(:disabled),
.auth-page .btn-outline-danger:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.auth-page a {
    color: #667eea;
}

.auth-page a:hover {
    color: #5a6fd4;
}
</style>
`;

// Template: auth/pages/RegisterPage.mst
templates['auth/pages/RegisterPage.mst'] = `<div class="auth-page register-page min-vh-100 d-flex align-items-center py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-lg border-0">
                    <div class="card-body p-4 p-md-5">
                        <!-- Logo and Header -->
                        <div class="text-center mb-4">
                            {{#logoUrl}}
                            <img src="{{logoUrl}}" alt="{{appName}}" class="mb-3" style="max-height: 60px;">
                            {{/logoUrl}}
                            <h2 class="h3 mb-2">{{messages.registerTitle}}</h2>
                            <p class="text-muted">{{messages.registerSubtitle}}</p>
                        </div>

                        <!-- Error Alert -->
                        {{#error}}
                        <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
                            <i class="bi bi-exclamation-triangle-fill me-2"></i>
                            <div>{{error}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {{/error}}

                        <!-- Registration Form -->
                        <form data-action="register" novalidate>
                            <!-- Name Field -->
                            <div class="mb-3">
                                <label for="registerName" class="form-label">
                                    <i class="bi bi-person me-1"></i>Full Name
                                </label>
                                <input
                                    type="text"
                                    class="form-control form-control-lg"
                                    id="registerName"
                                    placeholder="John Doe"
                                    value="{{name}}"
                                    data-field="name"
                                    data-action="updateField"
                                    data-action-keydown="handleKeyPress"
                                    required
                                    {{#isLoading}}disabled{{/isLoading}}>
                            </div>

                            <!-- Email Field -->
                            <div class="mb-3">
                                <label for="registerEmail" class="form-label">
                                    <i class="bi bi-envelope me-1"></i>Email Address
                                </label>
                                <input
                                    type="email"
                                    class="form-control form-control-lg"
                                    id="registerEmail"
                                    placeholder="name@example.com"
                                    value="{{email}}"
                                    data-field="email"
                                    data-action="updateField"
                                    data-action-keydown="handleKeyPress"
                                    required
                                    {{#isLoading}}disabled{{/isLoading}}>
                            </div>

                            <!-- Password Field -->
                            <div class="mb-3">
                                <label for="registerPassword" class="form-label">
                                    <i class="bi bi-lock me-1"></i>Password
                                </label>
                                <div class="input-group">
                                    <input
                                        type="{{#showPassword}}text{{/showPassword}}{{^showPassword}}password{{/showPassword}}"
                                        class="form-control form-control-lg"
                                        id="registerPassword"
                                        placeholder="Create a strong password"
                                        value="{{password}}"
                                        data-field="password"
                                        data-action="updateField"
                                        data-action-keydown="handleKeyPress"
                                        required
                                        {{#isLoading}}disabled{{/isLoading}}>
                                    <button
                                        class="btn btn-outline-secondary"
                                        type="button"
                                        data-password-field="password"
                                        data-action="togglePassword"
                                        {{#isLoading}}disabled{{/isLoading}}>
                                        <i class="bi bi-eye{{#showPassword}}-slash{{/showPassword}}"></i>
                                    </button>
                                </div>

                                <!-- Password Strength Indicator -->
                                {{#passwordStrength}}
                                <div class="mt-2">
                                    <div class="progress" style="height: 5px;">
                                        <div class="progress-bar {{#passwordStrength}}
                                            {{#weak}}bg-danger{{/weak}}
                                            {{#fair}}bg-warning{{/fair}}
                                            {{#good}}bg-info{{/good}}
                                            {{#strong}}bg-success{{/strong}}
                                        {{/passwordStrength}}"
                                        role="progressbar"
                                        style="width: {{#passwordStrength}}
                                            {{#weak}}25%{{/weak}}
                                            {{#fair}}50%{{/fair}}
                                            {{#good}}75%{{/good}}
                                            {{#strong}}100%{{/strong}}
                                        {{/passwordStrength}}">
                                        </div>
                                    </div>
                                    <small class="text-{{#passwordStrength}}
                                        {{#weak}}danger{{/weak}}
                                        {{#fair}}warning{{/fair}}
                                        {{#good}}info{{/good}}
                                        {{#strong}}success{{/strong}}
                                    {{/passwordStrength}}">
                                        Password strength: {{passwordStrength}}
                                    </small>
                                </div>
                                {{/passwordStrength}}
                            </div>

                            <!-- Confirm Password Field -->
                            <div class="mb-3">
                                <label for="registerConfirmPassword" class="form-label">
                                    <i class="bi bi-lock-fill me-1"></i>Confirm Password
                                </label>
                                <div class="input-group">
                                    <input
                                        type="{{#showConfirmPassword}}text{{/showConfirmPassword}}{{^showConfirmPassword}}password{{/showConfirmPassword}}"
                                        class="form-control form-control-lg {{^passwordMatch}}is-invalid{{/passwordMatch}}"
                                        id="registerConfirmPassword"
                                        placeholder="Re-enter your password"
                                        value="{{confirmPassword}}"
                                        data-field="confirmPassword"
                                        data-action="updateField"
                                        data-action-keydown="handleKeyPress"
                                        required
                                        {{#isLoading}}disabled{{/isLoading}}>
                                    <button
                                        class="btn btn-outline-secondary"
                                        type="button"
                                        data-password-field="confirmPassword"
                                        data-action="togglePassword"
                                        {{#isLoading}}disabled{{/isLoading}}>
                                        <i class="bi bi-eye{{#showConfirmPassword}}-slash{{/showConfirmPassword}}"></i>
                                    </button>
                                    {{^passwordMatch}}
                                    <div class="invalid-feedback">
                                        Passwords do not match
                                    </div>
                                    {{/passwordMatch}}
                                </div>
                            </div>

                            <!-- Terms and Conditions -->
                            {{#termsUrl}}
                            <div class="form-check mb-4">
                                <input
                                    class="form-check-input"
                                    type="checkbox"
                                    id="acceptTerms"
                                    data-field="acceptTerms"
                                    data-action="updateField"
                                    {{#acceptTerms}}checked{{/acceptTerms}}
                                    required
                                    {{#isLoading}}disabled{{/isLoading}}>
                                <label class="form-check-label" for="acceptTerms">
                                    I agree to the
                                    <a href="#" class="text-decoration-none" data-url="{{termsUrl}}" data-action="openLink">
                                        Terms of Service
                                    </a>
                                    {{#privacyUrl}}
                                    and
                                    <a href="#" class="text-decoration-none" data-url="{{privacyUrl}}" data-action="openLink">
                                        Privacy Policy
                                    </a>
                                    {{/privacyUrl}}
                                </label>
                            </div>
                            {{/termsUrl}}

                            <!-- Register Button -->
                            <button
                                type="submit"
                                class="btn btn-primary btn-lg w-100 mb-3"
                                {{#isLoading}}disabled{{/isLoading}}
                                {{#termsUrl}}{{^acceptTerms}}disabled{{/acceptTerms}}{{/termsUrl}}>
                                {{#isLoading}}
                                <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                                Creating account...
                                {{/isLoading}}
                                {{^isLoading}}
                                <i class="bi bi-person-plus me-2"></i>Create Account
                                {{/isLoading}}
                            </button>
                        </form>

                        <!-- Login Link -->
                        <div class="text-center mt-4">
                            <p class="mb-0">
                                Already have an account?
                                <a href="#" class="text-decoration-none fw-semibold" data-action="login">
                                    Sign in
                                </a>
                            </p>
                        </div>
                    </div>
                </div>

                <!-- Additional Help Text -->
                <div class="text-center mt-3">
                    <small class="text-muted">
                        <i class="bi bi-shield-check me-1"></i>Your information is secure and encrypted
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.auth-page {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.auth-page .card {
    backdrop-filter: blur(10px);
    background: rgba(255, 255, 255, 0.98);
    border-radius: 1rem;
}

.auth-page .form-control:focus,
.auth-page .form-check-input:focus {
    border-color: #667eea;
    box-shadow: 0 0 0 0.25rem rgba(102, 126, 234, 0.25);
}

.auth-page .btn-primary {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border: none;
}

.auth-page .btn-primary:hover:not(:disabled) {
    background: linear-gradient(135deg, #5a6fd4 0%, #68428e 100%);
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
}

.auth-page a {
    color: #667eea;
}

.auth-page a:hover {
    color: #5a6fd4;
}

.progress {
    background-color: #e9ecef;
}
</style>
`;

// Template: components/TablePage.mst
templates['components/TablePage.mst'] = `<div class="table-page-container">
  <!-- Header Section -->
  {{#title}}
  <div class="table-page-header mb-3">
    <h2 class="page-title mb-2">{{title}}</h2>
    {{#description}}
    <p class="page-description text-muted">{{description}}</p>
    {{/description}}
  </div>
  {{/title}}

  <!-- Table Container - Child view will render here -->
  <div id="{{tableContainerId}}" class="table-container" data-table-page="{{pageName}}">
    <!-- Table child view will be automatically rendered here -->
  </div>

  <!-- Status Bar -->
  {{#showStatus}}
  <div class="table-status-bar mt-3">
    <div class="d-flex align-items-center justify-content-between flex-wrap gap-2">
      <div class="status-info d-flex align-items-center gap-3">
        {{#showRecordCount}}
        <small class="text-muted">
          <i class="bi bi-database me-1"></i>
          <span data-status="record-count">{{recordCount}}</span> records
        </small>
        {{/showRecordCount}}

        {{#showLastUpdated}}
        <small class="text-muted">
          <i class="bi bi-clock-history me-1"></i>
          Updated: <span data-status="last-updated">{{lastUpdated}}</span>
        </small>
        {{/showLastUpdated}}
      </div>

      {{#loadError}}
      <span class="error-indicator text-danger" data-status="error" style="display: none;">
        <i class="bi bi-exclamation-triangle me-1"></i>
        <span class="error-text">{{loadError}}</span>
      </span>
      {{/loadError}}
    </div>
  </div>
  {{/showStatus}}
</div>
`;

// Export templates
export default templates;

export const auth_pages_ForgotPasswordPage_mst = templates['auth/pages/ForgotPasswordPage.mst'];
export const auth_pages_LoginPage_mst = templates['auth/pages/LoginPage.mst'];
export const auth_pages_RegisterPage_mst = templates['auth/pages/RegisterPage.mst'];
export const components_TablePage_mst = templates['components/TablePage.mst'];

// Helper functions

/**
 * Get a template by key
 * @param {string} key - Template key (e.g., "auth/pages/LoginPage.mst")
 * @returns {string|undefined} Template content or undefined if not found
 */
export function getTemplate(key) {
  // Handle different path formats
  const normalizedKey = key
    .replace(/^\//, "")  // Remove leading slash
    .replace(/^src\//, "")  // Remove src/ prefix
    .replace(/\\/g, "/");  // Normalize path separators
  
  return templates[normalizedKey] || templates[key];
}

/**
 * Check if a template exists
 * @param {string} key - Template key
 * @returns {boolean} True if template exists
 */
export function hasTemplate(key) {
  return getTemplate(key) !== undefined;
}

/**
 * Get all template keys
 * @returns {string[]} Array of template keys
 */
export function getTemplateKeys() {
  return Object.keys(templates);
}

/**
 * Get template count
 * @returns {number} Number of templates
 */
export function getTemplateCount() {
  return Object.keys(templates).length;
}

// Hot Module Replacement support
if (import.meta.hot) {
  import.meta.hot.accept();
}